### ISSUE TITLE
Is this a SHA-3?

### ISSUE THREAD

**Issue by ericelliott** [xaevik/cuid.net#12]
**Describe the bug**

Cuid2 should use SHA-3, which uses the [Keccak sponge construction](https://en.wikipedia.org/wiki/Sponge_function), which may be better than the Merkle-Damgård construction, the bases of several [insecure hash](https://www.win.tue.nl/hashclash/rogue-ca/) algorithms, and also the basis of SHA-512. What you want is SHA3-512.

**Comment by xaevik** [comment]
@ericelliott you are correct, the current implementation is not SHA-3, the documentation does not make that clear.

Further reading, shows this is a current pain point as well, https://github.com/dotnet/runtime/issues/20342. I am replacing the implementation with BouncyCastle.

**Comment by ericelliott** [comment]
Tada!
